// Copyright (C) 2015, Pawel Tomulik <ptomulik@meil.pw.edu.pl>
//
// Distributed under the Boost Software License, Version 1.0.
// (See accompanying file LICENSE_1_0.txt or copy at
//  http://www.boost.org/LICENSE_1_0.txt)

// txpl/test_config.hpp

/** // doc: txpl/test_config.hpp {{{
 * \file txpl/test_config.hpp
 * \todo Write documentation
 */ // }}}
#ifndef TXPL_TEST_CONFIG_HPP
#define TXPL_TEST_CONFIG_HPP

//////////////////////////////////////////////////////////////////////////////
// If you want to disable particular test module, uncomment one of the
// following definitions.
//////////////////////////////////////////////////////////////////////////////

// #define TXPL_TEST_SKIP_AST_NODE
// #define TXPL_TEST_SKIP_AST_NODES
// #define TXPL_TEST_SKIP_LEXER_GET_CHAR
// #define TXPL_TEST_SKIP_LEXER_GET_CONTENT
// #define TXPL_TEST_SKIP_LEXER_GET_DEC_DIGIT
// #define TXPL_TEST_SKIP_LEXER_GET_DEC_NUMBER
// #define TXPL_TEST_SKIP_LEXER_GET_HEX_DIGIT
// #define TXPL_TEST_SKIP_LEXER_GET_HEX_NUMBER
// #define TXPL_TEST_SKIP_LEXER_GET_INT
// #define TXPL_TEST_SKIP_LEXER_GET_OCT_DIGIT
// #define TXPL_TEST_SKIP_LEXER_GET_OCT_NUMBER
// #define TXPL_TEST_SKIP_LEXER_GET_QCHAR
// #define TXPL_TEST_SKIP_LEXER_GET_QREGEX
// #define TXPL_TEST_SKIP_LEXER_GET_QSTRING
// #define TXPL_TEST_SKIP_LEXER_GET_REAL
// #define TXPL_TEST_SKIP_LEXER_GET_REGEX_CHAR
// #define TXPL_TEST_SKIP_LEXER_GET_WORD
// #define TXPL_TEST_SKIP_LEXER_TOKEN
// #define TXPL_TEST_SKIP_LEXER_TOKENIZE
// #define TXPL_TEST_SKIP_LEXER_TOKEN_T
// #define TXPL_TEST_SKIP_LEXER_TRY_CHAR
// #define TXPL_TEST_SKIP_LEXER_TRY_DEC_DIGIT
// #define TXPL_TEST_SKIP_LEXER_TRY_DEC_NUMBER
// #define TXPL_TEST_SKIP_LEXER_TRY_HEX_DIGIT
// #define TXPL_TEST_SKIP_LEXER_TRY_HEX_NUMBER
// #define TXPL_TEST_SKIP_LEXER_TRY_INT
// #define TXPL_TEST_SKIP_LEXER_TRY_OCT_DIGIT
// #define TXPL_TEST_SKIP_LEXER_TRY_OCT_NUMBER
// #define TXPL_TEST_SKIP_LEXER_TRY_QCHAR
// #define TXPL_TEST_SKIP_LEXER_TRY_QREGEX
// #define TXPL_TEST_SKIP_LEXER_TRY_QSTRING
// #define TXPL_TEST_SKIP_LEXER_TRY_REAL
// #define TXPL_TEST_SKIP_LEXER_TRY_REGEX_CHAR
// #define TXPL_TEST_SKIP_LEXER_TRY_SPACES
// #define TXPL_TEST_SKIP_LEXER_TRY_TOKEN
// #define TXPL_TEST_SKIP_LEXER_TRY_WORD
// #define TXPL_TEST_SKIP_LEXER_TRY_WORD_CHAR
// #define TXPL_TEST_SKIP_PARSER_PARSE_IMPL_BRACED_EXPR
// #define TXPL_TEST_SKIP_PARSER_PARSE_IMPL_EXPR0
// #define TXPL_TEST_SKIP_PARSER_PARSE_IMPL_EXPR5
// #define TXPL_TEST_SKIP_PARSER_PARSE_IMPL_EXPR6
// #define TXPL_TEST_SKIP_PARSER_PARSE_IMPL_EXPR7
// #define TXPL_TEST_SKIP_PARSER_PARSE_IMPL_EXPR8
// #define TXPL_TEST_SKIP_PARSER_PARSE_IMPL_EXPR9
// #define TXPL_TEST_SKIP_PARSER_PARSE_IMPL_EXPR10
// #define TXPL_TEST_SKIP_PARSER_PARSE_IMPL_EXPR11
// #define TXPL_TEST_SKIP_PARSER_PARSE_IMPL_EXPR12
// #define TXPL_TEST_SKIP_PARSER_PARSE_IMPL_EXPR13
// #define TXPL_TEST_SKIP_PARSER_PARSE_IMPL_EXPR14
// #define TXPL_TEST_SKIP_PARSER_PARSE_IMPL_LITERAL
// #define TXPL_TEST_SKIP_PARSER_PARSE_IMPL_NAME
// #define TXPL_TEST_SKIP_PARSER_PARSE_IMPL_UNARY_EXPR
// #define TXPL_TEST_SKIP_VM_BASIC_TYPES
// #define TXPL_TEST_SKIP_VM_DISAMBIGUATE
// #define TXPL_TEST_SKIP_VM_DISAMBIGUATE_TYPE
// #define TXPL_TEST_SKIP_VM_EVAL_BINARY_AND
// #define TXPL_TEST_SKIP_VM_EVAL_BINARY_BITAND
// #define TXPL_TEST_SKIP_VM_EVAL_BINARY_BITOR
// #define TXPL_TEST_SKIP_VM_EVAL_BINARY_DIV
// #define TXPL_TEST_SKIP_VM_EVAL_BINARY_EQ
// #define TXPL_TEST_SKIP_VM_EVAL_BINARY_GE
// #define TXPL_TEST_SKIP_VM_EVAL_BINARY_GT
// #define TXPL_TEST_SKIP_VM_EVAL_BINARY_LE
// #define TXPL_TEST_SKIP_VM_EVAL_BINARY_LSHIFT
// #define TXPL_TEST_SKIP_VM_EVAL_BINARY_LT
// #define TXPL_TEST_SKIP_VM_EVAL_BINARY_MINUS
// #define TXPL_TEST_SKIP_VM_EVAL_BINARY_MOD
// #define TXPL_TEST_SKIP_VM_EVAL_BINARY_MUL
// #define TXPL_TEST_SKIP_VM_EVAL_BINARY_NEQ
// #define TXPL_TEST_SKIP_VM_EVAL_BINARY_OR
// #define TXPL_TEST_SKIP_VM_EVAL_BINARY_PLUS
// #define TXPL_TEST_SKIP_VM_EVAL_BINARY_RSHIFT
// #define TXPL_TEST_SKIP_VM_EVAL_BINARY_XOR
// #define TXPL_TEST_SKIP_VM_EVAL_UNARY_OP
// #define TXPL_TEST_SKIP_VM_OBJECT
// #define TXPL_TEST_SKIP_VM_OBJECT_ERASE
// #define TXPL_TEST_SKIP_VM_OBJECT_FIND
// #define TXPL_TEST_SKIP_VM_OBJECT_INSERT
// #define TXPL_TEST_SKIP_VM_OP_T
// #define TXPL_TEST_SKIP_VM_SCOPE
// #define TXPL_TEST_SKIP_VM_SCOPE_ERASE
// #define TXPL_TEST_SKIP_VM_SCOPE_FIND
// #define TXPL_TEST_SKIP_VM_SCOPE_INSERT
// #define TXPL_TEST_SKIP_VM_SCOPE_LOOKUP
// #define TXPL_TEST_SKIP_VM_SYMBOL
// #define TXPL_TEST_SKIP_VM_TREE_ERASER
// #define TXPL_TEST_SKIP_VM_TREE_FINDER
// #define TXPL_TEST_SKIP_VM_TREE_INSERTER
// #define TXPL_TEST_SKIP_VM_VALUE

#endif /* TXPL_TEST_CONFIG_HPP */
// vim: set expandtab tabstop=2 shiftwidth=2:
// vim: set foldmethod=marker foldcolumn=4:
